<template>
  <component :is="resolvedIcon" v-if="isLucide" :class="customClass" />
  <span
    v-else
    class="select-none leading-none inline-flex items-center justify-center font-normal"
    :class="customClass"
  >
    {{ icon }}
  </span>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import {
  Activity,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Award,
  Banknote,
  BarChart2,
  BookOpen,
  Box,
  Boxes,
  Brain,
  Briefcase,
  Building,
  Building2,
  Calculator,
  Calendar,
  CalendarRange,
  Check,
  CircleAlert,
  CircleHelp,
  ClipboardCheck,
  Coins,
  Compass,
  Contact,
  Cpu,
  DollarSign,
  DoorOpen,
  Ellipsis,
  Eye,
  Feather,
  FileText,
  Flag,
  FlaskConical,
  Folder,
  Frown,
  Gauge,
  Gavel,
  Gem,
  Gift,
  Globe,
  Goal,
  GraduationCap,
  Grid3x3,
  Hammer,
  HandCoins,
  Handshake,
  HardHat,
  Heart,
  HeartPulse,
  HelpCircle,
  Image,
  Info,
  Key,
  KeyRound,
  Landmark,
  Layers,
  LayoutGrid,
  Lightbulb,
  LineChart,
  Link,
  ListChecks,
  ListOrdered,
  Map,
  Megaphone,
  Meh,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Mic,
  Microscope,
  Milestone,
  MonitorPlay,
  Mountain,
  Newspaper,
  Package,
  Palette,
  PieChart,
  Pill,
  Plane,
  Plus,
  Presentation,
  Puzzle,
  Receipt,
  Repeat,
  Route,
  Ruler,
  Scale,
  Scissors,
  ScrollText,
  Settings,
  Shapes,
  Share2,
  ShieldAlert,
  Shirt,
  ShoppingBag,
  Sparkles,
  Split,
  Star,
  Store,
  Swords,
  Table2,
  Tag,
  Target,
  Telescope,
  TrendingUp,
  Type,
  User,
  UserCheck,
  UserCog,
  UserMinus,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  Workflow,
  Wrench,
  Zap,
} from 'lucide-vue-next'

const props = withDefaults(
  defineProps<{
    icon?: string | null
    fallback?: string
    customClass?: string
  }>(),
  {
    icon: '',
    fallback: 'file-text',
    customClass: 'w-4 h-4 text-current',
  },
)

// Emojis mapping to Lucide Icons
const emojiMap: Record<string, any> = {
  '📄': FileText,
  '📂': Folder,
  '🤔': HelpCircle,
  '🙋': UserCheck,
  '🙎': UserMinus,
  '✂️': Scissors,
  '✂': Scissors,
  '📈': LineChart,
  '🏅': Award,
  '🎩': GraduationCap,
  '😟': Frown,
  '💎': Gem,
  '📣': Megaphone,
  '🎙️': Mic,
  '🎙': Mic,
  '🤝': Handshake,
  '👁️': Eye,
  '👁': Eye,
  '😐': Meh,
  '🦾': Cpu,
  '✈️': Plane,
  '✈': Plane,
  '💊': Pill,
  '💼': Briefcase,
  '🧩': Puzzle,
  '🌟': Star,
  '🛍️': ShoppingBag,
  '🛍': ShoppingBag,
  '🧠': Brain,
  '🎯': Target,
  '⚙️': Settings,
  '⚙': Settings,
  '👔': Shirt,
  '⭐': Star,
  '👤': User,
  '🔧': Wrench,
  '➡️': ArrowRight,
  '⬅️': ArrowLeft,
  '⬅': ArrowLeft,
  '🪪': Contact,
  '🗓️': Calendar,
  '🗓': Calendar,
  '🏁': Flag,
  '📐': Ruler,
  '💰': Coins,
  '💸': Banknote,
  '💵': DollarSign,
  '🔮': Compass,
  '🚨': AlertTriangle,
  '🔑': Key,
  '🧪': FlaskConical,
  '➕': Plus,
  '✔️': Check,
  '✔': Check,
  '🏢': Building,
  '👷‍♂️': HardHat,
  '👷': HardHat,
  '❓': HelpCircle,
  '🚩': Flag,
  ℹ️: Info,
  ℹ: Info,
  '⚖️': Scale,
  '⚖': Scale,
}

// Lucide icon name mapping (normalized to lowercase, alphanumeric only)
const nameMap: Record<string, any> = {
  activity: Activity,
  award: Award,
  banknote: Banknote,
  barchart2: BarChart2,
  bookopen: BookOpen,
  box: Box,
  boxes: Boxes,
  briefcase: Briefcase,
  building2: Building2,
  calculator: Calculator,
  calendarrange: CalendarRange,
  check: Check,
  circlealert: CircleAlert,
  circlehelp: CircleHelp,
  clipboardcheck: ClipboardCheck,
  coins: Coins,
  compass: Compass,
  contact: Contact,
  dooropen: DoorOpen,
  ellipsis: Ellipsis,
  eye: Eye,
  feather: Feather,
  filetext: FileText,
  flag: Flag,
  flaskconical: FlaskConical,
  gauge: Gauge,
  gavel: Gavel,
  gem: Gem,
  gift: Gift,
  globe: Globe,
  goal: Goal,
  grid3x3: Grid3x3,
  hammer: Hammer,
  handcoins: HandCoins,
  handshake: Handshake,
  heart: Heart,
  heartpulse: HeartPulse,
  helpcircle: HelpCircle,
  image: Image,
  keyround: KeyRound,
  landmark: Landmark,
  layers: Layers,
  layoutgrid: LayoutGrid,
  lightbulb: Lightbulb,
  linechart: LineChart,
  link: Link,
  listchecks: ListChecks,
  listordered: ListOrdered,
  map: Map,
  megaphone: Megaphone,
  messagecircle: MessageCircle,
  messagesquare: MessageSquare,
  messagessquare: MessagesSquare,
  microscope: Microscope,
  milestone: Milestone,
  monitorplay: MonitorPlay,
  mountain: Mountain,
  newspaper: Newspaper,
  package: Package,
  palette: Palette,
  piechart: PieChart,
  plus: Plus,
  presentation: Presentation,
  puzzle: Puzzle,
  receipt: Receipt,
  repeat: Repeat,
  route: Route,
  ruler: Ruler,
  scale: Scale,
  scrolltext: ScrollText,
  settings: Settings,
  shapes: Shapes,
  share2: Share2,
  shieldalert: ShieldAlert,
  shoppingbag: ShoppingBag,
  sparkles: Sparkles,
  split: Split,
  star: Star,
  store: Store,
  swords: Swords,
  table2: Table2,
  tag: Tag,
  target: Target,
  telescope: Telescope,
  trendingup: TrendingUp,
  type: Type,
  user: User,
  usercog: UserCog,
  userplus: UserPlus,
  userround: UserRound,
  users: Users,
  usersround: UsersRound,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
}

const normalize = (name: string) => {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '')
}

const resolvedIcon = computed(() => {
  if (!props.icon) {
    return nameMap[normalize(props.fallback)] || FileText
  }
  const trimmed = props.icon.trim()
  if (emojiMap[trimmed]) {
    return emojiMap[trimmed]
  }
  const normalized = normalize(trimmed)
  if (nameMap[normalized]) {
    return nameMap[normalized]
  }
  // If not mapped:
  // If it is a short string (e.g. an emoji), return null to let the template render it.
  // Otherwise, return the fallback icon.
  const isShort = Array.from(trimmed).length <= 2
  if (isShort) {
    return null
  }
  return nameMap[normalize(props.fallback)] || FileText
})

const isLucide = computed(() => resolvedIcon.value !== null)
</script>
